# Site settings
title: Yigit Mersin
description: Yigit Mersin personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yigit Mersin
user_description: I have a generalist technical background and worked as a software specialist in aviation e-learning & hospitality domains. I like to tackle with technical problems & love every kind of guitar nerd.
user_title: Technical Advocate | Discourse
email: n/a
github_username: yigitm

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
